interface Test {
	integerPrimitive: number;
	integerReference: number;
	string: string;
	booleanPrimitive: boolean;
	booleanReference: boolean;
	doublePrimitive: number;
	doubleReference: number;
	floatPrimitive: number;
	floatReference: number;
	charPrimitive: string;
	charReference: string;
	bytePrimitive: number;
	byteReference: number;
	shortPrimitive: number;
	shortReference: number;
	longPrimitive: number;
	longReference: number;
	set: string[];
	hashSet: string[];
	list: number[];
	arrayList: number[];
	queue: number[];
	arrayQueue: number[];
	deque: SomeClass[];
	arrayDeque: SomeClass[];
	collection: Something[];
	arrayCollection: Something[];
	map: { [key: string]: number; };
	hashMap: { [key: string]: SomeClass; };
	restricted: boolean;
}
