interface Test {
	integerPrimitive: number;
	integerReference: number;
	string: string;
	booleanPrimitive: boolean;
	booleanReference: boolean;
	doublePrimitive: number;
	doubleReference: number;
	floatPrimitive: number;
	floatReference: number;
	charPrimitive: string;
	charReference: string;
	bytePrimitive: number;
	byteReference: number;
	shortPrimitive: number;
	shortReference: number;
	longPrimitive: number;
	longReference: number;
	set: String[];
	hashSet: String[];
	list: Integer[];
	arrayList: Integer[];
	queue: Long[];
	arrayQueue: Long[];
	deque: SomeClass[];
	arrayDeque: SomeClass[];
	collection: Something[];
	arrayCollection: Something[];
	map: { [key: String]: Integer; };
	hashMap: { [key: String]: Integer; };
	restricted: boolean;
}
